spring:
  datasource:
    url: jdbc:mysql://${FLOODIT_DATABASE_HOST:localhost}:${FLOODIT_DATABASE_PORT:3306}/${FLOODIT_DATABASE_NAME:floodit}
    username: ${FLOODIT_DATABASE_USER:floodit}
    password: ${FLOODIT_DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
